server:
  port: 5001
spring:
  datasource:
    url: jdbc:postgresql://localhost:54333/lingo
    username: postgres
    password: secret
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
